WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, C.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN CTE C ON E.PARENT_ID = C.ID
)

SELECT COUNT(ID) AS COUNT, GENERATION FROM CTE AS A
WHERE NOT EXISTS (
    SELECT 1 FROM CTE AS B
    WHERE A.ID = B.PARENT_ID
)
GROUP BY GENERATION
