-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF AS F
INNER JOIN (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) AS J
ON F.SHIPMENT_ID = J.SHIPMENT_ID
ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3



